version: "3"
services: 
  backend:
    container_name: backend
    image: ghcr.io/eosdg/server
    build:
        context: ./backend
    ports: ['3420:3420']
  frontend:
    container_name: frontend
    image: ghcr.io/eosdg/client
    build:
        context: ./frontend
    ports: ['80:80']
  
