version: "3"
services: 
  backend:
    container_name: backend
    build:
        context: ./backend
    ports: ['3420:3420']
  frontend:
    container_name: frontend
    build:
        context: ./frontend
    ports: ['80:80']
  
