name: Docker Image Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build the Docker image
      working-directory: ./backend
      run: docker build . --file Dockerfile --tag backend:$(date +%s)
